# Generated by Django 2.1.7 on 2019-03-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('budget', models.CharField(choices=[('Small project', 'Small project ($250-750 USD)'), ('Medium project', 'Medium project ($750-1500 USD)'), ('Big project', 'Big project($1500-30000 USD)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type_of_user', models.CharField(choices=[('Client', 'C'), ('Freelancer', 'F')], max_length=1)),
                ('public_key_PATH', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
