# Generated by Django 2.1.7 on 2019-04-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190420_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contry',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
