# Generated by Django 2.1.7 on 2019-05-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_publication_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
