# Generated by Django 2.1.7 on 2019-05-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190520_0014'),
    ]

    operations = [
      
     
     
    ]
