# Generated by Django 2.1.7 on 2019-05-20 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190520_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('rechazado', 'rechazado'), ('aceptado', 'aceptado'), ('en revision', 'en revision')], max_length=25)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='users.Publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='postulados',
            field=models.ManyToManyField(related_name='se_postula', through='users.Postulados', to=settings.AUTH_USER_MODEL),
        ),
    ]
