# Generated by Django 2.1.7 on 2019-05-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190520_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='postulados',
        ),
    ]
