# Generated by Django 2.1.7 on 2019-05-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_publication_postulados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulados',
            name='state',
            field=models.CharField(choices=[('rechazado', 'rechazado'), ('aceptado', 'aceptado'), ('en revision', 'en revision')], default='en revision', max_length=25),
        ),
    ]
