# Generated by Django 2.1.7 on 2019-05-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190520_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='budget',
            field=models.CharField(choices=[('Small project ($250-750 USD)', 'Small project ($250-750 USD)'), ('Medium project ($750-1500 USD)', 'Medium project ($750-1500 USD)'), ('Big project ($1500-30000 USD)', 'Big project($1500-30000 USD)')], max_length=50),
        ),
    ]
