# Generated by Django 2.1.7 on 2019-06-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190529_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calification',
            field=models.IntegerField(default=5),
        ),
    ]
