# Generated by Django 2.1.7 on 2019-06-04 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.DateField()),
                ('payment', models.IntegerField(default=0)),
                ('client_signature', models.CharField(max_length=255, unique=True)),
                ('freelancer_signature', models.CharField(max_length=255, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
