# Generated by Django 2.1.7 on 2019-06-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190605_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client_signature',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contract',
            name='freelancer_signature',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
